### ISSUE TITLE
glsl-mode hangs when trying to install

### ISSUE THREAD

**Issue by danieljamesross** [jimhourihan/glsl-mode#11]
I have been trying to install `glsl-mode` via MELPA using the `package-list-package` interface in GUI emacs without success. The package hangs and emacs freezes.

**Comment by jimhourihan** [comment]
Did you figure out the problem? I am unable to reproduce using 20200501.2304

**Comment by danieljamesross** [comment]
Yup, it installs now. I didn't do anything new. Perhaps some temp bug in MELPA?

**Comment by jimhourihan** [comment]
I removed trailing whitespace which was apparently an issue in the past. I don’t understand how MELPA could be sensitive to that but perhaps that fixed it. Thanks for informing me (although I missed the notification).
