### ISSUE TITLE
gl_FragCoord isn't syntax highlighted 

### ISSUE THREAD

**Issue by kresdjan** [jimhourihan/glsl-mode#14]
The built-in variable `gl_FragCoord` is highlighted.
![gl_FragCoord cleaned](https://user-images.githubusercontent.com/17638455/145692761-c21e6994-9f62-47c6-a43c-c13c6246bda8.png)

**Comment by jimhourihan** [comment]
Paste the text instead of an image. Its head to tell what's going on. I typed in what I see here and it worked for me.
