### ISSUE TITLE
What version of the GPL?

### ISSUE THREAD

**Issue by tarsius** [jimhourihan/glsl-mode#8]
The permission statement in library header does not specify what version of the GPL this is released under. The statement should read something like:

```lisp
;; This file is free software: you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published
;; by the Free Software Foundation, either version 3 of the License,
;; or (at your option) any later version.

;; This file is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this file.  If not, see <http://www.gnu.org/licenses/>.
```

Thanks!

**Comment by tarsius** [comment]
Friendly ping!

**Comment by jimhourihan** [comment]
The permission statement is correct for when it was originally included. If the original author decides to v3 his code I'll be happy to change this as well.

"If the Program does not specify a version number of the license, you may choose any version ever published by the Free Software Foundation"

**Comment by tarsius** [comment]
> If the original author decides to v3 his code I'll be happy to change this as well.

Do you know who that is.

> "If the Program does not specify a version number of the license, you may choose any version ever published by the Free Software Foundation"

If I understand that correctly, you could pick a version without the permission of the original author. If you don't want to do that, then please add a line `;; License: GPL` to the header. That would allow me to automatically extract that piece of information. I am doing that for a few thousand packages on the Emacsmirror and am trying to get the number of unlicensed packages, packages with incompatible licenses, and packages whose licenses I cannot extract down.

Thanks!

**Comment by tarsius** [comment]
My license extraction tool now has a special case for this package.

**Comment by tarsius** [comment]
@xdecoret, @Xadeck is one of you the author of this package?

If so, could you please give us explicit permission to make the above change.

If so, would you prefer if we changed to "either version **3** of the License, or (at your option) any later version" or "either version **1** of the License, or (at your option) any later version".

**Comment by Xadeck** [comment]
Damn. I haven't worked on this for 10 years. And I'm now a vim user, no longer a emacs one. Do whatever you want with the license.

**Comment by tarsius** [comment]
Thanks!
