### ISSUE TITLE
Negative number literals do not highlight correctly

### ISSUE THREAD

**Issue by awr1** [jimhourihan/glsl-mode#9]
![image](https://user-images.githubusercontent.com/41453959/58213244-08341080-7cb7-11e9-9b9c-01766ac6314c.png)
as an example.

**Comment by jimhourihan** [comment]
Hi @awr1, glsl-mode doesn't do any highlighting of numbers. If your cc-mode or a minor mode is doing that it might need a better regex for numbers. Another possibility is that the mode doing the highlighting somehow recognizes that RHS is not a vec3: you need to explicitly provide a constructor for the value:

    vec3 a = vec3(0.5, 0.5, 0.5);
    vec3 b = vec3(-0.5, -0.5, -0.5);
